### ISSUE TITLE
My task is missing

### ISSUE THREAD

**Issue by aspekt19** [koii-network/koii-node#4]
My task is missing, and with it the 500 KOII I stake. Now I don't have a single active task to complete.
<img width="1177" alt="Снимок экрана 2023-05-23 в 22 42 05" src="https://github.com/koii-network/desktop-node/assets/36282486/803e82a7-4b8b-4e31-83a6-3d25779ab917">

**Comment by smith-and-web** [comment]
Hi @aspekt19, we recently had to reset our testnet due to a fork that occurred when updating the task contract. I'd be happy to airdrop you your stake back. Please provide me with your address.

The tasks will be populated again shortly. We have to register them again so you'll have to perform a stake and run.

**Comment by aspekt19** [comment]
> Hi @aspekt19, we recently had to reset our testnet due to a fork that occurred when updating the task contract. I'd be happy to airdrop you your stake back. Please provide me with your address.
> 
> 
> 
> The tasks will be populated again shortly. We have to register them again so you'll have to perform a stake and run.

Okay, I got it. I'll wait for the update. My wallet:  
2eoAKLUy2iMKMky9P7XoV7Z5ngfb4CWLDn8RpzzZNYhc

**Comment by smith-and-web** [comment]
> 

Good to go. Sorry about that and thank you for being an ambassador!
